apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: comp-proj
  namespace: platform-system
spec:
  description: comp-proj-app-demo services
  sourceRepos:
    - https://github.com/scg-sre/scg-asgn-app-demo-deployment
  destinations:
    - { server: https://kubernetes.default.svc, namespace: 'backend-*' }
    - { server: https://kubernetes.default.svc, namespace: 'frontend-*' }
  clusterResourceWhitelist:
    - { group: '', kind: Namespace }
  namespaceResourceWhitelist:
    - { group: '*', kind: '*' }
  roles:
    - name: read-only
      policies:
        - p, proj:comp-proj:read-only, applications, get, comp-proj/*, allow
      groups:
        - comp:dev-team
    - name: deploy
      policies:
        - p, proj:comp-proj:deploy, applications, sync, comp-proj/*, allow
      groups:
        - comp:sre-team
        - comp:release-managers
