apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: web-success-rate
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 1m
      count: 5
      successCondition: result[0] >= 0.99
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc:9090
          query: |
            sum(rate(nginx_http_requests_total{
              service="{{args.service-name}}",
              status!~"5.."
            }[1m]))
            /
            sum(rate(nginx_http_requests_total{
              service="{{args.service-name}}"
            }[1m]))
