apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: comp-proj-sit
resources:
  - ../../base

components:
  - ../../variants/non-prod

patches:
  - target: { kind: Rollout, name: frontend }
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/comp.io~1env
        value: sit
  - target: { kind: PodDisruptionBudget, name: frontend }
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
      - op: add
        path: /spec/selector/matchLabels/comp.io~1env
        value: sit
  - { path: version.yml, target: { kind: Rollout, name: frontend } }
  - { path: replicas.yml, target: { kind: Rollout, name: frontend } }
  - target: { kind: Ingress, name: frontend }
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: appsit.gpevn.com

configMapGenerator:
  - name: frontend-settings
    files: [settings.yml]
  - name: frontend-static
    files: [static.yml]
