apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  strategy:
    blueGreen:
      activeService: backend-stable
      previewService: backend-preview
      autoPromotionEnabled: false          # require manual promote (UI/CLI)
      scaleDownDelaySeconds: 300           # keep old RS for 5m post-promote (fast rollback)
      abortScaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
          - templateName: backend-success-rate
          - templateName: backend-latency-p99
        args:
          - name: service-name
            value: backend-preview
      postPromotionAnalysis:
        templates:
          - templateName: backend-success-rate
        args:
          - name: service-name
            value: backend-stable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: backend
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: backend
          image: public.ecr.aws/c5a3w2d1/backend:placeholder        # overridden by envs/<env>/version.yml
          imagePullPolicy: IfNotPresent
          ports:
            - { name: http, containerPort: 8080, protocol: TCP }
            - { name: mgmt, containerPort: 8081, protocol: TCP }
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/etc/backend/settings.yml
            - name: MANAGEMENT_SERVER_PORT
              value: "8081"
          volumeMounts:
            - { name: settings, mountPath: /etc/backend, readOnly: true }
            - { name: tmp,      mountPath: /tmp }
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits:   { cpu: 1000m, memory: 1Gi }
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: mgmt }
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: mgmt }
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ALL] }
      volumes:
        - name: settings
          configMap:
            name: backend-settings    # rewritten by kustomize → backend-settings-<hash>
        - name: tmp
          emptyDir: { sizeLimit: 256Mi }
