apiVersion: v1
kind: Service
metadata:
  name: api-stable
  labels: { app.kubernetes.io/name: api }
spec:
  selector: { app.kubernetes.io/name: api }
  ports:
    - { name: http, port: 80, targetPort: http }
---
apiVersion: v1
kind: Service
metadata:
  name: api-canary
  labels: { app.kubernetes.io/name: api }
spec:
  selector: { app.kubernetes.io/name: api }
  ports:
    - { name: http, port: 80, targetPort: http }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  labels: { app.kubernetes.io/name: api }
