apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-dev

resources:
  - ../../base

components:
  - ../../variants/non-prod
  - ../../variants/canary-fast

patches:
  - { path: version.yml, target: { kind: Rollout, name: web } }
  - { path: replicas.yml, target: { kind: Rollout, name: web } }

configMapGenerator:
  - name: web-settings
    files: [settings.yml]
  - name: web-static
    files: [static.yml]
