logging:
  level:
    root: INFO
    com.comp.backend: INFO
  format: json

server:
  shutdown: graceful
  http:
    timeout: 5s

features:
  newSearch: true
  darkMode: true
  experimentalCheckout: false
