apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: comp-proj-prod

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      comp.io/env: prod
resources:
  - ../../base

components:
  - ../../variants/prod
  - ../../variants/high-traffic

patches:
  - { path: version.yml, target: { kind: Rollout, name: frontend } }
  - { path: replicas.yml, target: { kind: Rollout, name: frontend } }

configMapGenerator:
  - name: frontend-settings
    files: [settings.yml]
  - name: frontend-static
    files: [static.yml]
