logging:
  level:
    root: INFO
    com.comp.backend: DEBUG
  format: json

server:
  shutdown: graceful
  http:
    timeout: 10s

features:
  newSearch: true
  darkMode: true
  experimentalCheckout: true
