apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: comp-proj-prod
resources:
  - ../../base

components:
  - ../../variants/prod
  - ../../variants/high-traffic

patches:
  - target: { kind: PodDisruptionBudget, name: backend }
    patch: |-
      - op: add
        path: /spec/selector/matchLabels/comp.io~1env
        value: prod
  - target: { kind: Rollout, name: backend }
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/comp.io~1env
        value: prod
  - path: version.yml
    target: { kind: Rollout, name: backend }
  - path: replicas.yml
    target: { kind: Rollout, name: backend }

configMapGenerator:
  - name: backend-settings
    files: [settings.yml]
  - name: backend-static
    files: [static.yml]
